---
- name: OS aktualisieren
  hosts: cluster01
  become: true
  
  tasks:
    
    # Update/Upgrade Tasks
    - name: Paketlisten aktualisieren (apt update)
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Pakete aktualisieren (apt upgrade)
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
    
    # Neustart Tasks
    - name: Prüfen, ob ein Neustart erforderlich ist
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
    
    - name: System neu starten (wenn nötig)
      ansible.builtin.reboot:
        msg: "System wird neu gestartet, da Updates dies erfordern."
        connect_timeout: 5
        reboot_timeout: 600
      when: reboot_required.stat.exists
    
    # Backup der SSH-Konfiguration (wenn Neustart erforderlich)
    - name: Backup der SSH-Konfiguration erstellen (wenn Neustart erforderlich)
      ansible.builtin.copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.backup-{{ ansible_date_time.date }}
        remote_src: yes
      ignore_errors: yes
      when: reboot_required.stat.exists
